### ISSUE TITLE
docs errors in http://docs.canarytrace.com/docs/references/awesome/

### ISSUE THREAD

**Issue by kretmir** [canarytrace/documentation#41]
This glossary contains explain used technologies and terms in the Canarytrace ecosystem.
->> Co to tady dela, neni to copy paste? Pokud ano melo by se to pravit stejne jako u glossary tzn
This glossary contains an explanation of the technologies and terms used in the Canarytrace ecosystem.

**Comment by rdpanek** [comment]
jop, uz tomu rozumim
