### ISSUE TITLE
docs errors in http://docs.canarytrace.com/docs/references/troubleshooting/

### ISSUE THREAD

**Issue by kretmir** [canarytrace/documentation#42]
This glossary contains explain used technologies and terms in the Canarytrace ecosystem.
->> opet copy pasta z glossary?

Some version of elasticsearch return ResponseError: parse_exception **and in this** case don't use compression.
->>
Some version of elasticsearch return ResponseError: parse_exception. **In this case** don't use compression.

This print settings of **elatsicsearch** connection, request and response events and payload to stdout.
->>
This print settings of **elasticsearch** connection, request and response events and payload to stdout.

You don’t have sufficient resources **of** your k8s cluster for run Canarytrace instance.
->>
You don’t have sufficient resources **on** your k8s cluster for run Canarytrace instance.

**Comment by rdpanek** [comment]
@kretmir I'dont understand this 
```
->> opet copy pasta z glossary?
```
