### ISSUE TITLE
Rules: definition of internal default rules

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#46]
### IDEA

Canarytrace Listener will be automatically check the rules of quality a web application.

Sources:
- https://httparchive.org
- https://www.smashingmagazine.com/2021/01/front-end-performance-2021-free-pdf-checklist/

**Comment by rdpanek** [comment]
### CSS & JS
- must be compresed by `gzip` or `br`

**Comment by rdpanek** [comment]
- [ ] test 1
- [ ] test 2

**Comment by Tomas-Kostka** [comment]
### HTTP/2
- HTTP/2 is widely supported and offers a performance boost
- mind the different approach compared to HTTP/1.1 (e.g. No of assets sent over a single HTTP/2 connection)

**Comment by Tomas-Kostka** [comment]
### text/plain compression
- `br` (or at least `gzip`) is used for plain text compression
- You can enable Brotli even on CDNs that don’t support it yet (with a service worker).

**Comment by Tomas-Kostka** [comment]
### HPACK compression for HTTP/2
- If using HTTP/2, implement HPACK compression for HTTP response headers
- a note: Some HTTP/2 servers may not fully support the specification.

**Comment by Tomas-Kostka** [comment]
### HTTP/2 Server Push
- If using HTTP/2, HTTP/2 Server Push should be used

**Comment by Tomas-Kostka** [comment]
### HTTP/2 Server Push - DEPRECATED
- HTTP/2 Server Push is being removed from Chrome 
- see https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ

**Comment by Tomas-Kostka** [comment]
### HTTP/3
- HTTP/3 provides a number of improvements compared to HTTP/2
-- see https://blog.cloudflare.com/http3-the-past-present-and-future/
- HTTP/3 is still work in progress. But major browsers have implementations ready. Some CDNs support QUIC and HTTP/3 too.  Google services are already running over HTTP/3.

**Comment by Tomas-Kostka** [comment]
### Minimal response body size for 404
- the 404 response body size sent to the browser must be tiny
- the best way is the cached version served by a CDN
-- see https://nooshu.github.io/blog/2020/08/25/you-should-be-testing-your-404-pages-web-performance/

**Comment by Tomas-Kostka** [comment]
### well known - low-hanging fruits
- lazy-loaded images
- unsized images
- legacy format images
- synchronous scripts
- web fonts that aren't used
- icon fonts
- - see https://gist.github.com/tkadlec/683b26344cde774170b94c0fcf0088b4

**Comment by Tomas-Kostka** [comment]
### Never more 404 on favicon.ico
- By default a browser automatically looks for the favicon.ico in the websites root directory (if a <link rel="icon"> isn’t present). If no icon is found, a server will respond with a 404 page.
-- see https://love2dev.com/blog/web-performance-tip-make-sure-you-have-a-favicon/

**Comment by Tomas-Kostka** [comment]
### LCP (Largest Contentful Paint) < 2.5s

**Comment by Tomas-Kostka** [comment]
### FID (First Input Delay) < 100ms
--see https://web.dev/vitals/#core-web-vitals

**Comment by Tomas-Kostka** [comment]
### Cumulative Layout Shift (CLS) < 0.1
-- see https://web.dev/vitals/#core-web-vitals

**Comment by Tomas-Kostka** [comment]
### Remove unused CSS/JavaScript. 
- use CSS and JavaScript code coverage in Chrome to learn which code has been executed/applied and which hasn’t. Once you've detected unused code,find those modules and lazy load with import().

**Comment by Tomas-Kostka** [comment]
### Constrain the impact of third-party scripts
- A single third-party script may call a long tail of scripts. 
-- Consider using service workers by racing the resource download with a timeout. 
-- Establish a Content Security Policy (CSP) to restrict the impact of third-party scripts, e.g. disallowing the download of audio or video. 
-- Embed scripts via iframe, so scripts don't have access to the DOM. Sandbox them, too. 
-- Load third-party scripts only once the app has initialized. 
-- Watch out for anti-flicker snippets.
see https://www.smashingmagazine.com/2021/01/front-end-performance-2021-free-pdf-checklist/

**Comment by Tomas-Kostka** [comment]
### HTTP headers set properly
- Without proper HTTP cache headers (=`Cache-Control`) setting, browsers will set them automatically
- No unnecessary headers (e.g. `server`, `expires`, `x-powered-by`, `pragma`, `x-frame-options`, `X-XSS-Protection`, `x-cache`, `via`, `p3p`, `x-aspnet-version`, `x-ua-compatible` and others)
-- see https://www.fastly.com/blog/headers-we-dont-want
-

**Comment by Tomas-Kostka** [comment]
###  use `defer` instead of `async` to load critical JavaScript asynchronously
- With defer, browser doesn’t execute scripts until HTML is parsed. 
-- So, unless you need JavaScript to execute before start render, it’s better to use `defer`
see https://calendar.perfplanet.com/2016/prefer-defer-over-async/#attributes

**Comment by Tomas-Kostka** [comment]
### Not use BOTH `async` and `defer`
- Modern browsers support both, but whenever both attributes are used, `async` will always win.

**Comment by Tomas-Kostka** [comment]
### Optimized images (ToDo)
- with Squoosh, mozjpeg, guetzli, pingo and SVGOMG, 
- AVIF/WebP served with an image CDN

**Comment by Tomas-Kostka** [comment]
### used resource hints to speed up delivery
- with `dns-lookup`, `preconnect`, `prefetch`, `preload` and `prerender`

**Comment by Tomas-Kostka** [comment]
### assets cached in a service worker cache
- assets such as fonts, styles, JavaScript and images

**Comment by Tomas-Kostka** [comment]
### Optimized images (ToDo)
- with Squoosh, mozjpeg, guetzli, pingo and SVGOMG,
- AVIF/WebP served with an image CDN

**Comment by Tomas-Kostka** [comment]
### budget for critical-path resources (CSS, JS, HTML, and data) should be max. 170KB gzipped
- to reach TTI under 5 seconds for first load (on 3G network + midrange Android)
see https://infrequently.org/2017/10/can-you-afford-it-real-world-web-performance-budgets/

**Comment by Tomas-Kostka** [comment]
### Serve legacy code only to legacy browsers
- with `<script type="module">` and `module/nomodule` pattern

**Comment by rdpanek** [comment]
## Final table

| title | Index | Condition | Min | Score |
|:-:|:-:|:-:|-|-|
| Failed check your page! | c.report | test step failed | 2 | 10 |
| Encoding of response with Javascript files must contains gzip or brotli compression. | c.response | gzip or br missing in headers.content-encoding | 10 | 40 |
| Green | 71 | 100 |  |  |
